### ISSUE TITLE
Error after install with sample data

### ISSUE THREAD

**Issue by justinbeaty** [MahoCommerce/maho#30]
First, I git cloned maho/main, composer install, and then run the install CLI:

```bash
./maho install --license_agreement_accepted yes --locale en_US --timezone "America/Los_Angeles" --default_currency USD --db_host localhost --db_name maho --db_user maho --db_pass password --url "https://store.example.com/" --secure_base_url "https://store.example.com/" --use_secure 1 --use_secure_admin 1 --admin_lastname admin --admin_firstname admin --admin_email "admin@admin.com" --admin_username admin --admin_password passwordpassword1 --sample_data 1
```

Then I load the frontend, and get this error:

```bash
Error in file: "/home/www-data/work/maho/git/app/code/core/Mage/Eav/sql/eav_setup/upgrade-1.6.0.1-1.6.0.2.php" - SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'eav_attribute_option_swatch' already exists, query was: CREATE TABLE `eav_attribute_option_swatch` (
  `value_id` int UNSIGNED NOT NULL auto_increment COMMENT 'Value Id' ,
  `option_id` int UNSIGNED NOT NULL default '0' COMMENT 'Option Id' ,
  `value` varchar(255) NULL default NULL COMMENT 'Value' ,
  `filename` varchar(255) NULL default NULL COMMENT 'Filename' ,
  PRIMARY KEY (`value_id`),
  UNIQUE `IDX_EAV_ATTRIBUTE_OPTION_VALUE_OPTION_ID` (`option_id`),
  CONSTRAINT `FK_EAV_ATTR_OPT_SWATCH_OPT_ID_EAV_ATTR_OPT_OPT_ID` FOREIGN KEY (`option_id`) REFERENCES `eav_attribute_option` (`option_id`) ON DELETE CASCADE ON UPDATE CASCADE
) COMMENT='Eav Attribute Option Swatch' ENGINE=INNODB charset=utf8 COLLATE=utf8_general_ci

#0 /home/www-data/work/maho/git/app/code/core/Mage/Core/Model/Resource/Setup.php(627): Mage::exception()
#1 /home/www-data/work/maho/git/app/code/core/Mage/Core/Model/Resource/Setup.php(421): Mage_Core_Model_Resource_Setup->_modifyResourceDb()
#2 /home/www-data/work/maho/git/app/code/core/Mage/Core/Model/Resource/Setup.php(305): Mage_Core_Model_Resource_Setup->_upgradeResourceDb()
#3 /home/www-data/work/maho/git/app/code/core/Mage/Core/Model/Resource/Setup.php(220): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /home/www-data/work/maho/git/app/code/core/Mage/Core/Model/App.php(437): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /home/www-data/work/maho/git/app/code/core/Mage/Core/Model/App.php(344): Mage_Core_Model_App->_initModules()
#6 /home/www-data/work/maho/git/app/Mage.php(689): Mage_Core_Model_App->run()
#7 /home/www-data/work/maho/git/public/index.php(58): Mage::run()
#8 {main}
```

And indeed I already have that table, but `core_resource` has this row `('eav_setup','1.6.0.1','1.6.0.1')`. So I fix it with:
```sql
update core_resource set version='1.6.0.2', data_version='1.6.0.2' where code='eav_setup';
```

Reload, and then one more error:

```bash
Error in file: "/home/www-data/work/maho/git/app/code/core/Mage/Customer/sql/customer_setup/upgrade-1.6.2.0.4-1.6.2.0.5.php" - SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'customer_flowpassword' already exists, query was: CREATE TABLE `customer_flowpassword` (
  `flowpassword_id` int UNSIGNED NOT NULL auto_increment COMMENT 'Flow password Id' ,
  `ip` varchar(50) NOT NULL COMMENT 'User IP' ,
  `email` varchar(255) NOT NULL COMMENT 'Requested email for change' ,
  `requested_date` varchar(255) NOT NULL default '0000-00-00 00:00:00' COMMENT 'Requested date for change' ,
  PRIMARY KEY (`flowpassword_id`),
  INDEX `IDX_CUSTOMER_FLOWPASSWORD_EMAIL` (`email`),
  INDEX `IDX_CUSTOMER_FLOWPASSWORD_IP` (`ip`),
  INDEX `IDX_CUSTOMER_FLOWPASSWORD_REQUESTED_DATE` (`requested_date`)
) COMMENT='Customer flow password' ENGINE=INNODB charset=utf8 COLLATE=utf8_general_ci

#0 /home/www-data/work/maho/git/app/code/core/Mage/Core/Model/Resource/Setup.php(627): Mage::exception()
#1 /home/www-data/work/maho/git/app/code/core/Mage/Core/Model/Resource/Setup.php(421): Mage_Core_Model_Resource_Setup->_modifyResourceDb()
#2 /home/www-data/work/maho/git/app/code/core/Mage/Core/Model/Resource/Setup.php(305): Mage_Core_Model_Resource_Setup->_upgradeResourceDb()
#3 /home/www-data/work/maho/git/app/code/core/Mage/Core/Model/Resource/Setup.php(220): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /home/www-data/work/maho/git/app/code/core/Mage/Core/Model/App.php(437): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /home/www-data/work/maho/git/app/code/core/Mage/Core/Model/App.php(344): Mage_Core_Model_App->_initModules()
#6 /home/www-data/work/maho/git/app/Mage.php(689): Mage_Core_Model_App->run()
#7 /home/www-data/work/maho/git/public/index.php(58): Mage::run()
#8 {main}
```

So I run:

```sql
update core_resource set version='1.6.2.0.5', data_version='1.6.2.0.5' where code='customer_setup';
```

And it loads. But I can't figure out why this error happens. The `maho-sample-data/db_data.sql` file doesn't seem to contain either of these tables, so they should be created as the result of the upgrade scripts, but then why isn't core_resource being updated?

**Comment by fballiano** [comment]
we were talking with @tmewes about the same thing earlier, but I tested in my local installation (both in a cloned core and a child project created with maho-starter and I didn't see any problem

<img width="595" alt="Screenshot_2024-09-24_alle_17 36 56" src="https://github.com/user-attachments/assets/e58d9ee4-177d-4275-9b38-df3ff41a8dfd">

**Comment by fballiano** [comment]
but now I'm checking https://github.com/MahoCommerce/maho-sample-data/blob/main/db_preparation.sql and I delete everything from core_resource and then the records get created in https://raw.githubusercontent.com/MahoCommerce/maho-sample-data/refs/heads/main/db_data.sql

which is weird, I don't know why I left it this way but I think it's better to remove the core_resource from the db_data.sql, right? am I missing something?

**Comment by fballiano** [comment]
I've updated the maho-sample-data, can you re-try the installation?

**Comment by justinbeaty** [comment]
Yes, I think that's the issue. The commit (https://github.com/MahoCommerce/maho-sample-data/commit/f6db3d381e67376472710c42d2f95c36ddb4cca4) looks correct.

**Comment by justinbeaty** [comment]
> I've updated the maho-sample-data, can you re-try the installation?

Solved!

**Comment by fballiano** [comment]
nice!
